---
- name: Configure web server
  hosts: all
  gather_facts: false

  tasks:
    - name: Include the environment task file and set the variables
      include_tasks: tasks/environment.yml #include the tasks from the environment.yml file, specify the correct path to the file
      vars: #set the necessary variables
        iis_package_names:
          - Web-Server
          - Web-Asp-Net45

    - name: Import the site task file and set the variables
      import_tasks: tasks/site.yml #import the tasks from the site.yml files, specify the correct path
      vars: #set the necessary variables
        iis_site_path: C:\sites\projects
        iis_site_name: "DO417-projects"
        iis_site_port: 8080 #specify the correct port

    - name: Import the firewall task file and set the variable
      import_tasks: tasks/firewall.yml #import the task from the firewall.yml file, specify the correct path
      vars: #set the necessary variables
        iis_site_port: 8080 #specify the correct port

- name: Import test play file and set the variable
  import_playbook: plays/test.yml #import the play from the test.yml file, specify the correct path
  vars:
    url: 'http://win1.example.com:8080'
