---
- name: Configure a host using DSC
  hosts: all

  tasks:

    - name: Create a new directory
      win_dsc: #Replace with the correct module
        resource_name: File #Replace with the correct option
        DestinationPath: C:\DO417\dsc-usage-example #Replace with the correct option
        Ensure: Present #Replace with the correct option
        Type: Directory

    - name: Create a new file with text
      win_dsc: #Replace with the correct module
        resource_name: File #Replace with the correct option
        DestinationPath: C:\DO417\dsc-usage-example\new-file.txt #Replace with the correct option
        Contents: | #Replace with the correct option
            Hello
            This is the DO417 course.
        Ensure: Present
        Type: File

    - name: Copy a zip file to the managed host
      win_copy: #Replace with the correct module
        src: do417-example.zip
        dest: C:\DO417\dsc-usage-example\do417-example.zip

    - name: Extract a zip file in the new directory
      win_dsc: #Replace with the correct module
        resource_name: Archive #Replace with the correct option
        Destination: C:\DO417\dsc-usage-example\extracted-zip #Replace with the correct option
        Path: C:\DO417\dsc-usage-example\do417-example.zip
        Ensure: Present