- name: Create a scheduled task
  hosts: win1.example.com
  vars:
    # Create a variable for the script name
    ps_script: 'pingHosts.ps1'

  tasks:
      # Create a task to create the 'scripts' directory
    - name: Script directory is created
      win_file:
        path: C:\Scripts\
        state: directory

      # Create a task to send the PowerShell script
    - name: PowerShell script is transferred
      win_copy:
        src: "files//{{ ps_script }}"
        dest: C:\Scripts\

      # Create the scheduled task.
    - name: A scheduled task is created
      win_scheduled_task:
        name: QueryHosts
        description: >
          Run a PowerShell script that uses ping to reach a servers in the environment
        author: student@example.com
        enabled: true
        actions:
        - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
          arguments: >
            -ExecutionPolicy Unrestricted '-NonInteractive -File C:\Scripts\{{ ps_script }}'
        triggers:
        - type: boot
        - type: logon
        priority: 1
        state: present

      # Create a task to retrieve some information about the scheduled task.
    - name: Status of the task is retrieved
      win_scheduled_task_stat:
        name: QueryHosts
      changed_when: False
