---
#copy and paste all the tasks from the original playbook
- name: Create a new directory
  win_dsc: #replace with the correct module
    resource_name: File #replace with the correct option
    DestinationPath: "{{ directory_location }}" #replace with the correct option
    Ensure: Present #replace with the correct option
    Type: Directory #replace with the correct option

- name: Create a new file with text
  win_dsc:
    resource_name: File
    DestinationPath: "{{ file_name }}"
    Contents: |
        Hello
        This is the DO417 course.
    Ensure: Present
    Type: File

- name: Install a Windows feature
  win_dsc: #replace with the correct module
    resource_name: "{{ windows_resource }}" #replace with the correct option
    Name: "{{ feature_name }}" #replace with the correct option

- name: Copy a zip file to the managed host
  win_copy:
    src: "{{ zip_file_location }}"
    dest: "{{ zip_remote_location }}"

- name: Extract a zip file in the new directory
  win_dsc:
    resource_name: Archive
    Destination: "{{ zip_extracted_location }}"
    Path: "{{ zip_remote_location }}"
    Ensure: Present