---
- name: Deploying Files to Managed Hosts Lab
  hosts: all
  tasks:
    # Define a task to start the IIS Web Server
    - name: IIS Web Server started
      win_feature:
        name: Web-Server
        state: present

    # Define a task that deploys the index.html template
    - name: Hosts file template deployed
      win_template:
        src: templates/index.html.j2
        dest: C:\Inetpub\wwwroot\index.html
        backup: yes

    # Define a task that denies Write access to index.html for Users
    - name: User write permission is denied
      win_acl:
        path: C:\Inetpub\wwwroot\index.html
        user: Users
        rights: Write
        type: deny
        state: present
        
