---
- name: Creating AD groups and users
  hosts: all
  vars:
    domainname: EXAMPLE.COM
    user_password: RedHat123@!

  tasks:
      # Update the task to create a new group in the domain
    - name: New group in the "{{ domainname }}" is created
      win_domain_group:
        name: Review Group
        scope: global

      # Update the task to create a new user in the group
    - name: New user in the "{{ domainname }}" is created
      win_domain_user:
        name: oliver
        firstname: Oliver
        lastname: Stone
        password: "{{ user_password }}"
        state: present
        groups:
          - Domain Users
          - Review Group